CREATE VIEW BILLS_WITH_PRODUCTS AS 
	SELECT S.TYPE, NAME, PRICEVALUE, PRICECURRENCY, BILL_ID 
	FROM OFFERS O, BILLS B, SALESITEMS S 
	WHERE B.OFFER_ID = O.ID AND OFFEREDITEM_ID = S.ID 
		AND O.VALIDTO IS NULL AND S.VALIDTO IS NULL;
